import { Link, useParams } from "react-router-dom";
import { ChevronLeft, Printer } from "lucide-react";
import { formatAddress, useJobs, useSavedCalcs } from "../lib/jobs";
import { EDITION } from "../lib/nec/2023";

/**
 * Print-friendly job report (Pro export target). Uses light styling so it
 * prints clean; "Save as PDF" via the browser's print dialog. Works offline.
 */
export default function JobReport() {
  const { id } = useParams();
  const job = useJobs().find((j) => j.id === id);
  const calcs = useSavedCalcs().filter((c) => c.jobId === id);

  if (!job) {
    return (
      <div className="mx-auto max-w-2xl px-4 pt-10 text-center text-slate-500">
        <p>Job not found.</p>
        <Link to="/jobs" className="mt-3 inline-block text-brand">
          ← Back to jobs
        </Link>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white text-slate-900">
      <div className="no-print flex items-center justify-between border-b border-slate-200 px-4 py-3">
        <Link to={`/jobs/${job.id}`} className="flex items-center gap-1 text-slate-600">
          <ChevronLeft size={20} /> Back
        </Link>
        <button
          onClick={() => window.print()}
          className="flex items-center gap-1.5 rounded-lg bg-brand px-4 py-2 font-semibold text-white"
        >
          <Printer size={18} /> Print / Save as PDF
        </button>
      </div>

      <div className="mx-auto max-w-2xl px-6 py-6">
        <div className="mb-6 flex items-baseline justify-between border-b border-slate-300 pb-3">
          <h1 className="text-2xl font-bold">Codewire — Job Report</h1>
          <span className="text-sm text-slate-500">{EDITION.code}</span>
        </div>

        <h2 className="text-xl font-bold">
          {job.name}
          {job.jobNumber && (
            <span className="ml-2 text-base font-normal text-slate-500">
              #{job.jobNumber}
            </span>
          )}
        </h2>
        {formatAddress(job) && (
          <p className="text-slate-600">{formatAddress(job)}</p>
        )}
        {job.phone && <p className="text-slate-600">{job.phone}</p>}
        {job.notes && (
          <p className="mt-1 whitespace-pre-wrap text-sm text-slate-600">
            {job.notes}
          </p>
        )}

        <h3 className="mb-2 mt-6 text-sm font-semibold uppercase tracking-wide text-slate-500">
          Calculations ({calcs.length})
        </h3>
        {calcs.length === 0 ? (
          <p className="text-slate-500">No saved calculations.</p>
        ) : (
          <table className="w-full border-collapse text-sm">
            <thead>
              <tr className="border-b border-slate-300 text-left text-slate-500">
                <th className="py-2 pr-2">Item</th>
                <th className="py-2 pr-2">Inputs</th>
                <th className="py-2">Result</th>
              </tr>
            </thead>
            <tbody>
              {calcs.map((c) => (
                <tr key={c.id} className="border-b border-slate-200 align-top">
                  <td className="py-2 pr-2 font-semibold">{c.title}</td>
                  <td className="py-2 pr-2 text-slate-600">{c.summary}</td>
                  <td className="py-2 font-mono">{c.result}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}

        <p className="mt-8 border-t border-slate-200 pt-3 text-xs text-slate-400">
          Generated by Codewire. {EDITION.note} Field aid only — not a substitute
          for the code book or a licensed inspection.
        </p>
      </div>
    </div>
  );
}
